version: SEIMS-Win64.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2013
configuration: Release
platform: x64
services: mongodb
build:
  parallel: true
  verbosity: minimal
environment:
  global:
    GDAL_HOME: "C:\\gdal"
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_ENV: "cmd /E:ON /V:ON /C .\\doc\\ci\\appveyor\\run_with_env.cmd"
install:
  # download compiled gdal and install it
  - ps: mkdir C:\gdal | out-null
  - appveyor DownloadFile http://download.gisinternals.com/sdk/downloads/release-1800-x64-gdal-1-11-4-mapserver-6-4-3.zip -FileName gdalbin.zip
  - 7z x gdalbin.zip -oC:\gdal
  - appveyor DownloadFile http://download.gisinternals.com/sdk/downloads/release-1800-x64-gdal-1-11-4-mapserver-6-4-3-libs.zip -FileName gdallibs.zip
  - 7z x gdallibs.zip -oC:\gdal
  - "SET PATH=C:\\gdal;C:\\gdal\\bin;C:\\gdal\\data;C:\\gdal\\bin\\gdal\\apps;%PATH%"
  - "SET PATH=C:\\GDAL\\bin\\ms\\apps;C:\\GDAL\\bin\\curl;C:\\GDAL\\bin\\proj\\apps;%PATH%"
  - "SET GDAL_DATA=C:\\gdal\\bin\\gdal-data"
  - "SET GDAL_DIR=C:\\gdal"
  - ECHO "Filesystem C:/GDAL:"
  - ps: "ls \"C:/GDAL\""
  # compile mongo-c-driver
  - appveyor DownloadFile https://github.com/mongodb/mongo-c-driver/releases/download/1.5.5/mongo-c-driver-1.5.5.tar.gz -FileName mongo-c-driver-1.5.5.tar.gz
  - 7z x mongo-c-driver-1.5.5.tar.gz
  - 7z x mongo-c-driver-1.5.5.tar -oC:\
  - cd C:\mongo-c-driver-1.5.5
  - ps: "ls"
  - cd src\libbson
  - cmake -DCMAKE_INSTALL_PREFIX=C:\mongo-c-driver -G "Visual Studio 12 2013 Win64"
  - msbuild.exe ALL_BUILD.vcxproj
  - msbuild.exe INSTALL.vcxproj
  - cd ..\..
  - cmake -DCMAKE_INSTALL_PREFIX=C:\mongo-c-driver -DBSON_ROOT_DIR=C:\mongo-c-driver -G "Visual Studio 12 2013 Win64"
  - msbuild.exe ALL_BUILD.vcxproj
  - msbuild.exe INSTALL.vcxproj
  - "SET MONGOC_ROOT_DIR=C:\\mongo-c-driver"
  - "SET MONGOC_LIB_DIR=C:\\mongo-c-driver\\bin"
  - "SET PATH=C:\\mongo-c-driver\\bin;%PATH%"
  # install MS-MPI
  - cd C:\projects\seims
  - "powershell doc\\ci\\appveyor\\install-msmpi.ps1"
  - "doc\\ci\\appveyor\\SetEnvMPI.cmd"
build_script:
  - cd C:\projects\seims\seims
  - ps: "ls"
  - mkdir buildlongterm64
  - cd buildlongterm64
  # Build 64-bit LONGTERM release version on Windows, and build unittest.
  - cmake -G "Visual Studio 12 2013 Win64" .. -DARCH=64 -DUNITTEST=1
  - msbuild.exe SEIMS_LONGTERM_OMP_x64_ALL.sln /p:Configuration=Release
  - msbuild.exe INSTALL.vcxproj
  # Build 64-bit STORM release version on Windows, and build unittest.
  - cd ..
  - mkdir buildstorm64
  - cd buildstorm64
  - cmake -G "Visual Studio 12 2013 Win64" .. -DSTORM=1 -DARCH=64 -DUNITTEST=1
  - msbuild.exe SEIMS_STORM_OMP_x64_ALL.sln /p:Configuration=Release
  - msbuild.exe INSTALL.vcxproj
test_script:
  # Run unit test. TODO to complete unittest code.
  - C:\projects\seims\seims\bin\seims_ut_exec.exe
